server.port: 9090

zuul:
  routes:
    event:
      path: /event/**
      url: http://localhost:9443
    guest:
      path: /guest/**
      url: http://localhost:7443
    token:
      path: /token/**
      url: http://localhost:8080
#    jwt:
 #     path: /token/**
  #    url: http://localhost:8443
  sensitiveHeaders:

ribbon.eureka.enabled: false

# openid oauth-server config
security.oauth2.client.clientId: potluckPlanner
security.oauth2.client.clientSecret: potluckPlannerSecret
security.oauth2.resource.token-info-uri: http://localhost:8080/oauth/check_token

# via gateway
oidc:
  tokenEndpoint: http://localhost:8080/oauth/token
  tokenIssuer: http://localhost:8080/
  authorizationEndpoint: http://localhost:8080/oauth/authorize
  userInfoEndpoint: http://localhost:8080/api/users/me

#server.ssl.key-store=gatewayservice.jks
#server.ssl.key-store-password=olena123
#server.ssl.keyAlias=gatewayservice

gateway:
  cors-config:
    contentSecurityPolicy: "default-src blob: localhost:*, *.lakt.ca"
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - "http://localhost[:]*"
      - "https://localhost[:]*"
      - "http://*[.]lakt[.]ca"
      - "https://*[.]lakt[.]ca"
  config:
    appVersion: 1.0.0
    oathIntrospectionEndpoint: http://localhost:8080/oauth/check_token
    # throttling props
    # max requests config -  different for each service
    maxUserRequestsPerSec: 5000
    # TODO  - not impemented counters per service
    maxEventRequestsPerSec: 5000
    maxGuestRequestsPerSec: 5000
    maxMenuRequestsPerSec: 2000

logging:
  config: 'classpath:logback-spring.xml'
  level:
    com.olena.gateway: debug
    org.springframework.cloud: error
    org.springframework.boot: debug
    org.springframework.security : debug
    root: debug



