# reporting metrics to prometheus
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: prometheus,info,health
  endpoint:
    prometheus.enabled: true

server.port: 7443

spring.data.mongodb.uri: mongodb://localhost/guestdb

guest-service:
  cors-config:
    contentSecurityPolicy: "default-src blob: localhost:*, *.lakt.ca"
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - "http://localhost[:]*"
      - "https://localhost[:]*"
      - "http://*[.]lakt[.]ca"
      - "https://*[.]lakt[.]ca"
  config:
    appVersion: 1.0.0
    dbSchemaVersion: 1.0.0
    dishServiceUrl: http://localhost:6443/v1/dishes
    drinkServiceUrl: http://localhost:5443/v1/drinks

# mTLS related
#server.ssl.key-store: guestservice.jks
#server.ssl.key-store-password: olena123
#server.ssl.keyAlias: guestservice

# can not use curl to  guest service when uncommented
#server.ssl.client-auth:  need

# openid oath-server config
security:
  oauth2:
    resource.token-info-uri: http://localhost:8080/oauth/check_token
    client:
      clientId: potluckPlanner
      clientSecret: potluckPlannerSecret

# JWT related
#security.oauth2.resource.user-info-uri: https://localhost:8443/user
#security.oauth2.resource.jwt.keyUri: https://localhost:8443/oauth/token_key

logging:
  config: classpath:logback-spring.xml
  level:
    com.olena.guestservice: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.data.mongodb: error
    org.mongodb.driver: error
    root: debug