server.port=6443

server.ssl.key-store: dishservice.jks
server.ssl.key-store-password=olena123
server.ssl.keyAlias: dishservice

server.ssl.client-auth = need

#security.oauth2.resource.user-info-uri:https://localhost:8443/user
#security.oauth2.resource.jwt.keyUri: https://localhost:8443/oauth/token_key

spring.data.mongodb.uri=mongodb://localhost/dishdb

dish-service.config.dbSchemaVersion=1.0.0
