# reporting metrics to prometheus
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: prometheus,info,health
  endpoint:
    prometheus.enabled: true

server.port: 6443

spring.data.mongodb.uri: mongodb://localhost/dishdb

dish-service:
  cors-config:
    contentSecurityPolicy: "default-src blob: localhost:*, *.lakt.ca"
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - "http://localhost[:]*"
      - "https://localhost[:]*"
      - "http://*[.]lakt[.]ca"
      - "https://*[.]lakt[.]ca"
  config:
    appVersion: 1.0.0
    dbSchemaVersion: 1.0.0

# mTLS related
#server.ssl.key-store: dishservice.jks
#server.ssl.key-store-password: olena123
#server.ssl.keyAlias: dishservice

#server.ssl.client-auth :  need

# openid oath-server config
security:
  oauth2:
    resource.token-info-uri: http://localhost:8080/oauth/check_token
    client:
      clientId: potluckPlanner
      clientSecret: potluckPlannerSecret

# JWT related
#security.oauth2.resource.user-info-uri:https://localhost:8443/user
#security.oauth2.resource.jwt.keyUri: https://localhost:8443/oauth/token_key

logging:
  config: classpath:logback-spring.xml
  level:
    com.olena.dishservice: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.data.mongodb: error
    org.mongodb.driver: error
    root: debug
