server.port=5443

server.ssl.key-store: drinkservice.jks
server.ssl.key-store-password=olena123
server.ssl.keyAlias: drinkservice

server.ssl.client-auth = need

#security.oauth2.resource.user-info-uri:https://localhost:8443/user
#security.oauth2.resource.jwt.keyUri: https://localhost:8443/oauth/token_key

spring.data.mongodb.uri=mongodb://localhost/drinkdb

drink-service.config.dbSchemaVersion=1.0.0
