server.port: 9443

# DB config
spring:
  data.mongodb.uri: mongodb://localhost/eventdb
  cloud:
    stream:
      kafka:
        binder:
          zkNodes.brokers: localhost:2287
      bindings:
        output:
          # topic name
          destination: POTLUCK-EVENT-DEV
          content-type: application/json


# reporting metrics to prometheus
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: prometheus,info,health
  endpoint:
    prometheus.enabled: true

event-service:
  cors-config:
    contentSecurityPolicy: "default-src blob: localhost:*, *.lakt.ca"
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - "http://localhost[:]*"
      - "https://localhost[:]*"
      - "http://*[.]lakt[.]ca"
      - "https://*[.]lakt[.]ca"
  config:
    appVersion: 1.0.0
    dbSchemaVersion: 1.0.0
    guestServiceUrl: http://localhost:7443/v1/guests


# mTLS config
#server.ssl.key-store: eventservice.jks
#server.ssl.key-store-password: olena123
#server.ssl.keyAlias: eventservice

# openid oauth-server client  config
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/api/users/me
      token-info-uri: http://localhost:8080/oauth/check_token
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
    client:
      clientId: potluckPlanner
      clientSecret: potluckPlannerSecret

logging:
  config: classpath:logback-spring.xml
  level:
    com.olena.eventservice: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.cloud: debug
    org.springframework.data.mongodb: error
    org.mongodb.driver: error
    root: debug