server.port: 9443

# DB config
spring.data.mongodb.uri: mongodb://localhost/eventdb

# reporting metrics to prometheus
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: prometheus,info,health
  endpoint:
    prometheus.enabled: true

event-service:
  cors-config:
    contentSecurityPolicy: "default-src blob: localhost:*, *.lakt.ca"
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - "http://localhost[:]*"
      - "https://localhost[:]*"
      - "http://*[.]lakt[.]ca"
      - "https://*[.]lakt[.]ca"
  config:
     appVersion: 1.0.0
     dbSchemaVersion: 1.0.0
     guestServiceUrl: http://localhost:7443/v1/guests


# TLS config
#server.ssl.key-store: eventservice.jks
#server.ssl.key-store-password: olena123
#server.ssl.keyAlias: eventservice

# openid oauth-server client  config

#security.oauth2.client.clientId: potluckPlanner
#security.oauth2.client.clientSecret: potluckPlannerSecret
#security.oauth2.client.accessTokenUri: http://localhost:8080/oauth/token
#security.oauth2.client.userAuthorizationUri: http://localhost:8080/oauth/authorize
#security.oauth2.client.tokenName: oauth_token
#security.oauth2.client.authenticationScheme: query
#security.oauth2.client.clientAuthenticationScheme: form
#security.oauth2.client.scope: user

security:
  oauth2:
   # client:
    #  clientId: potluckPlanner
    #  clientSecret: potluckPlannerSecret
    #  accessTokenUri: http://localhost:8080/oauth/access_token
    #  userAuthorizationUri: http://localhost:8080/oauth/authorize
    #  clientAuthenticationScheme: form
    resource:
      user-info-uri: http://localhost:8080/api/users/me
      token-info-uri: http://localhost:8080/oauth/check_token
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

logging:
  config: classpath:logback-spring.xml
  level:
      com.olena.eventservice: debug
      org.springframework.security: debug
      org.springframework.web: debug
      org.springframework.data.mongodb: error
      org.mongodb.driver: error
      root: debug